creation_rules:
  - key_groups:
      - age:
          - age1730f3cxdyh56zw8xcvlmpa7u2x7353wu4u0e58kyx24rsefgp98sxehm6s
          - age1ygsq7dryah6w55dvp4g289y2uq9nxuvzp4sr5hkde970ucdtlqgsew6xzx
    path_regex: ^secrets\.yaml$
  - key_groups:
      - age:
          - age1730f3cxdyh56zw8xcvlmpa7u2x7353wu4u0e58kyx24rsefgp98sxehm6s
          - age1ygsq7dryah6w55dvp4g289y2uq9nxuvzp4sr5hkde970ucdtlqgsew6xzx
    path_regex: ^evals/questions\.enc\.yaml$
